version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/source/conf.py  # Utilise le conf.py dans docs/source/

python:
  install:
    - requirements: docs/requirements.txt
