from .boxplot import BoxPlot
from .barchart import BarChart
from .donut import Donut
from .heatmap import Heatmap
from .histogramme import Histogramme
from .linechart import LineChart
from .treemap import Treemap
from .scatterplot import ScatterPlot
import streamlit as st